### ISSUE TITLE
Afficher les vues rapprochees des 13 armes d alarmes

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#361]
Ici, nous détaillerons les contenus fonctionnels et graphiques de la page d'identification des armes d'alarmes.

# Tasks 

- [x] Afficher en préambule le texte suivant : "_Nous allons vous guider dans la détection d'une arme d'alarme. Voici les 13 modèles d'armes d'alarmes reconnues par décret. Veuillez sélectionner le modèle correspondant à votre arme, ou bien sélectionner "Aucune correspondance"._"
- [x] Afficher les photo des 13 armes d'alarmes.
- [x] Sur chacune des 13 photos, l'utilisateur doit pouvoir cliquer sur une loupe pour afficher une vue rapprochée du marquage de l'arme
- [x] Afficher au dessus de chacune des photos d'arme le nom de l'arme
- [x] Ajouter à côté de chaque nom d'arme d'alarme une case à cocher (choix unique).
- [x] En dessous des 13 images, ajouter une case à cocher avec le texte "Aucune correspondance sur les marquages". Cela permet à l'utilisateur de spécifier qu'il n'a à priori pas entre les main une arme d'alarme.
- [x] En fin de page, via un bouton "Suivant", l'utilisateur valide sa saisie et passe à l'étape de résultat

L'utilisateur doit pouvoir visualiser très finement les 13 marquages pour comparer avec l'arme qu'il a entre les mains.
