### ISSUE TITLE
Déployer le nouveau backend

### ISSUE THREAD

**Issue by thomashbrnrd** [datalab-mi/Basegun#379]
Passage du backend fastapi au backend Django (https://github.com/datalab-mi/basegun-backend).

# Tasks

- [ ] Faire tourner le nouveau backend sur l'env de Dev.
- [ ] Mettre en place postgres sur l'env de Dev.
- [ ] Vérifier que tout fonctionne normalement sur l'env de Dev.
- [ ] Passer à l'env de Staging.
- [ ] Passer en prod.

- [ ] récupérer les contacts Passage 2
- [ ] Prendre contact avec Passage 2 pour calendrier de mise en place de l'authentification des experts via Passage 2
