### ISSUE TITLE
Modification COPROJ 13/03

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#387]
Suite au COPROJ du 13/03 voici les modifications envisagées : 

# Tasks 

- [x] Introduire une page supplémentaire **qui ne fait pas incrémenter le stepper** qui introduit les consignes et la démarche d'identification des armes d'alarmes
- [x] Dans cette nouvelle page, voici le texte à ajouter : "Votre arme pourrait être une arme d'alarme, nous allons vous guider pour déterminer si c'en est une, et ce, **grâce aux marquages présents sur l'arme**. Voici les 13 modèles d'armes d'alarmes reconnues par arrêté. Vous pouvez obtenir une vue rapprochée des marquages de chaque modèle en cliquant sur le bouton de zoom. Veuillez sélectionner le modèle correspondant à votre arme, ou bien sélectionner "Aucune correspondance". 
- [x] Modifier le titre : pour "Identification d'une arme d'alarme"
![image](https://github.com/datalab-mi/Basegun/assets/150133063/6b3eea42-0269-4498-9612-29a08fe2d9b2)
- [x] Penser à une mise en forme de type disclaimer + picto adaptée
- [x] Confirmer la catégorie légale des armes d'alarme
