### ISSUE TITLE
Pre remplissage du mail de demande d avis

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#388]
En tant qu'utilisateur FSI, je souhaite accéder à un mail pré rempli pour accélérer/faciliter l'envoi de ma demande d'identification à ma permanence.

# Tasks
- [x] Destinataire : reprendre le mail de la permanence (PTS ou IRCGN)
- [x] Emetteur : reprendre le mail de l'utilisateur (déjà prérempli par l'appli de gestion des mails sur NEO ?)
- [x] En objet : [Basegun] Demande d'identification
- [x] En corps de mail : 
              NIGEND / matricule :
              N° de procédure : 
              Téléphone : 
              Service d'affectation : 
              Typologie de l'arme (épaule ou poing) : 
              Précision sur les marquages présents sur l'arme :
