### ISSUE TITLE
Ajouter les nouvelles consignes à l ecran de consignes de prise de photos

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#389]
En tant qu'utilisateur FSI, je dispose d'un écran de consignes de prise de photo m'indiquant l'ensemble des consignes à vérifier pour tirer le maximum des deux modèles d'IA et obtenir la catégorie légale de mon arme.

# Tasks

- [x] Afficher les consignes dans un encadrés permettant de souligner leur importance : 

1. Présenter la canon vers la droite
2. Ne photographier qu'une seule arme
3. Place l'arme en entier et au centre de la photo
4. Placer une carte à côté de l'arme (n'importe quelle carte au format standard)

- [x] afficher la photo d'exemple avec la picto associée
- [x] Bouton pour prendre la photo en bas de page
![image](https://github.com/datalab-mi/Basegun/assets/150133063/f9477b78-3785-4ae9-959a-23916ae301a2)

**Comment by ClemGerard** [comment]
Statut de l'issue ?
