### ISSUE TITLE
Implementer les RG integrant les mesures de Lcanon et Ltotale

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#400]
Voici les règles à implémenter pour pouvoir intégrer les longueurs dans la détermination de la catégorie légale : 

Les disclaimers sont à afficher dans l'encadré à la suite de la catégorie légale pressentie, et à la ligne.
Début du disclaimer : "Attention" en gras et en bleu Marianne, la suite du message en noir avec les indications en gras spécifiées ci-dessous.

# Tasks
- [x] Lancer le module de mesure seuleument sur les typologies concernées
- typologies concernées par le module de mesure:
    - semi auto style chasse
    - épaule à verrou
    - épaule à pompe
    - épaule à levier de sous-garde
    - épaule à un coup par canon

- typologies non concernées:
  - Revolver
  - pistolet semi auto
  - autre pistolets
  - pistolets à mecanisme ancien
  - epaule à mecanisme ancien
  - épaule semi auto style militaire milieu 20
  - épaule semi auto style militaire autre
- [x] Typologie "Epaule à levier de sous garde"  :
 - SI L_tot < 75 cm OU SI L_barrel < 40 cm : **Catégorie B**
 - SI L_tot > 75 cm ET SI  40 cm < L_barrel < 55 cm : **Catégorie B ou C**
 - SI L_tot > 75 cm ET SI L_barrel > 55 cm : **Catégorie C**
 - Afficher le disclaimer suivant pour **les deux derniers cas** : 
"**Attention** : Si la **capacité est supérieure à 11 munitions**, ou si le **canon est lisse** : **Catégorie B**
Si le **canon est rayé** : **Catégorie C**"

- [x] Typologie "Epaule à verrou"  : 
 - SI L_tot < 75 cm OU SI L_barrel < 40 cm : **Catégorie B**
 - SI L_tot > 75 cm ET SI  40 cm < L_barrel < 55 cm : **Catégorie B ou C**
 - SI L_tot > 75 cm ET SI L_barrel > 55 cm : **Catégorie C**
 - Afficher le disclaimer suivant pour **les deux derniers cas** : 
"**Attention** : Si la **capacité est supérieure à 11 munitions**, ou si le **canon est lisse** : **Catégorie B**
Si le **canon est rayé** : **Catégorie C**"

- [x] Typologie "Arme d'épaule semi auto style chasse" : 
 - Typologie  "Arme d'épaule semi auto style chasse"  : SI L_tot < 75 cm OU SI L_barrel < 40 cm : **Catégorie B**
 - Typologie  "Arme d'épaule semi auto style chasse"  : SI L_tot > 75 cm ET SI  40 cm < L_barrel < 55 cm : **Catégorie B ou C**
 - Typologie  "Arme d'épaule semi auto style chasse"  : SI L_tot > 75 cm ET SI L_barrel > 55 cm : **Catégorie C**
 - Afficher le disclaimer suivant pour **les deux derniers cas** : 
"Attention : Si la **capacité est supérieure à 3 munitions**, ou si le **canon est lisse** : Catégorie B
Si le **canon est rayé** : Catégorie C"

- [x] Typologie "Arme d'épaule à pompe" : 
- SI L_tot < 75 cm **OU** SI L_barrel < 55 cm : **Catégorie B**
- SI L_tot > 75 cm **ET** SI L_barrel > 55 cm : **Catégorie C**
- Afficher le disclaimer suivant pour le dernier cas : "Attention : Si la **capacité maximale (chambre comprise)
est supérieure à 5**, ou si **la crosse n’est pas fixe**, ou si le **canon est lisse** : Catégorie B"

- [x] Typologie "Arme d'épaule à 1 coup par canon" : 
- SI L_tot < 75 cm **OU** SI L_barrel < 40 cm : **Catégorie B**
- SI L_tot > 75 cm **ET** SI L_barrel > 40 cm : **Catégorie C**

- [x] Typologie "Arme d'épaule style militaire milieu 20e " : 
- **Catégorie A ou B**
- Afficher le disclaimer : "Attention : Si à l’origine l’arme était à répétition automatique puis a été
transformée en arme semi automatique, alors elle est de catégorie A.
Si l’arme possède **une crosse rétractable / pliable** et qu’en configuration la plus courte elle **mesure moins de 60 cm** : **Catégorie A**"

- [x] Typologie "Arme d'épaule style militaire autre" : 
 - **Catégorie A ou B**
 - Afficher le disclaimer : "Attention : Si à l’origine l’arme était à répétition automatique puis a été
transformée en arme semi automatique, alors elle est de catégorie A.
Si l’arme possède **une crosse rétractable / pliable** et qu’en configuration la plus courte elle **mesure moins de 60 cm** : **Catégorie A**"

**Comment by ClemGerard** [comment]
fournir une capture d'écran des différents cas possibles pour ajustement des visuels avec Elisabeth.

**Comment by ClemGerard** [comment]
Stand by en attendant le fix du backend.
