### ISSUE TITLE
Implement the new designs

### ISSUE THREAD

**Issue by ClemGerard** [datalab-mi/Basegun#427]
Issue globale sur l'implémentation des éléments graphiques concernant : l'écran de consigne, le feedback utilisateur sur l'absence de carte (post prise de photo+résultat), page de résultat.

# Tasks
- [x] Add Arrow
- [x] Add rectangles around the card
- [x] Change the text in the top rectangle
Figma here : https://www.figma.com/file/xFeslMOobBMugOp8AIvKDp/Basegun?type=design&node-id=2773-21769&mode=design

UPDATE SUITE AU COPROJ DU 24/04 : 
Reprendre le design de l'écran de résultat quand l'utilisateur n'a pas placé de carte à côté de l'arme au moment de prendre la photo.
- [ ] Placer l'écran qui prévient l'utilisateur qu'aucune carte n'a été détectée, juste après la prise de photo, en stipulant la typologie trouvée. _ATTENTION déclenchement_ quand Basegun trouve une arme d'épaule **(à verrou, à levier de sous garde, à un coup par canon, à pompe, semi auto style chasse, semi auto ou auto militaire autres, semi auto ou auto style milieu 20e)**, ET quand aucune carte n'est détectée.
![Chemin 1-Instruction](https://github.com/datalab-mi/Basegun/assets/150133063/dd6451b8-26a7-4e76-96a2-1ff511b1f66b)
- [ ] Placer en fin de parcours QUAND L'UTILISATEUR A CLIQUE SUR "Je souhaite tout de même poursuivre", l'écran Figma qui précise que l'utilisateur a un résultat peu précis sous les yeux dû à l'absence de carte sur la photo.
- [ ] Implémenter le trigger de non détection de carte, pour déclencher l'affichage de l'écran rappelant qu'il faut ajouter une carte ET l'écran de résultat associé
- [ ] Implémenter les éléments graphiques de la nouvelle page de résultat avec les différents encadrés du DSFR : on distingue plusieurs types de messages (spécifiés par le PO).
- [ ] Implémenter les designs "typologie", "disclaimer potentiel arme d'alarme ou factice" au format "encadrés" sur la page de résultat  intermédiaire

**Comment by ClemGerard** [comment]
Reprendre la dernière version de la capture d'écran vu avec Elisabeth.

**Comment by leihuayi** [comment]
mettre aussi à jour la page "prise de photo" avec ce qui est sur Figma :
- mettre à jour la photo "exemple d'une bonne photo"
- mettre à jour le texte d'instruction concernant la carte

**Comment by ClemGerard** [comment]
A voir avec les métiers le 24/04/2024 à quel moment on affiche l'information visuelle qu'une carte n'a pas été placée sur la photo.

**Comment by ClemGerard** [comment]
@ClemGerard décrire les niveaux d'affichage de message et spécifier les types de message associés à chaque niveau d'affichage
